2011-libra/notables

- app/components/index.js
- app/components/texteditor/Texteditor.css
- app/components/texteditor/texteditor.js
- app/components/texteditor/toolbar.js
- app/main.js
- package-lock.json
- package.json
- public/index.css
- public/index.html
___
**Notes:** Some features of the toolbar are buggy (ie: linking and code box) though it does semi-work
> Text editor

- app/components/texteditor/Texteditor.css
- app/components/texteditor/codeeditor.js
- app/components/texteditor/texteditor.js
___
___
**Notes** : File saves as plain text and not rich text as of yet.
> T1-FE Export: Created component to download rich text file

- app/components/navbar/dropdownmenu.js
- app/components/navbar/navbar.css
- app/components/navbar/navbar.js
- app/components/navbar/navitem.js
- app/main.js
- package-lock.json
- package.json
> FE: navbar with errors

- package.json
Added a script to ensure the docker image is available
> added docker script

- app/components/navbar/dropdownmenu.js
- app/components/navbar/navbar.css
- app/main.js
- package-lock.json
-Will only display drop down for setting
> T1 FE: Navbar. adjusted to only display dropdown for settings

- app/components/texteditor/texteditor.js
- app/components/texteditor/toolbar.js
- public/index.html
> T1-FE Export: Added Turndown library, converting HTML to MD via download

- app/components/import/Dropzone.css
- app/components/import/dropzone.js
- app/components/texteditor/texteditor.js
- app/components/texteditor/toolbar.js
- app/main.js
- package-lock.json
- package.json
- public/index.html
> T1-FE: Created import component for users to drag/drop and click to import files.

- app/components/texteditor/Texteditor.css
- app/components/texteditor/toolbar.js
T1-FE (Simple Code Snippet): Logic Added to Preprocess Code before Sending to Docker
> T1-FE (Simple Code Snippet): Logic Added to Preprocess Code before Sending to Docker

- app/components/navbar/nav.css
- app/components/navbar/nav.js
- app/components/texteditor/texteditor.js
- package-lock.json
-[ ] Added Hover effects to buttons
-[ ] Moved pre-existing logic to make nav export button functional
> T1-FE: Added styles and export functionality to nav

- app/components/texteditor/CodeBlock.js
- app/components/texteditor/Texteditor.css
- app/components/texteditor/texteditor.js
- app/components/texteditor/toolbar.js
-Styling
-Unique Token to Avoid Collision
-Updated Inline Code Block Attributes
> Inline code block

- app/components/texteditor/texteditor.js
> T1-FE: Added library to convert MD to HTML

- app/components/texteditor/texteditor.js
- public/index.html
> Testing import

- app/components/texteditor/texteditor.js
- app/components/texteditor/toolbar.js
> T1-FE: Fixed error in toolbar dropdown that dealt with the normal option

- app/components/navbar/nav.css
> T2-FE: Changed logo and name color to white

- app/components/import/Dropzone.css
- app/components/import/dropzone.js
- app/components/navbar/nav.css
- app/components/navbar/nav.js
> T2-FE: Edited/Styled drawer/dropzone component

- README.md
- package-lock.json
- package.json
Updated Readme.md.  Removed all references to the database. Added nodemon as a dev-dependency because we can't assume the user has it.
> T2-BE: updated readme with 'about' and client usage information

- app/components/navbar/nav.css
- app/components/navbar/nav.js
> T2-FE: Fixed alignment of navbar icons

- app/components/navbar/nav.js
- app/components/texteditor/toolbar.js
- Added 3 new conditions to throw alert when not selecting/highlighting text in the text editor for hyperlinking
- Renamed "Export" on the navbar to "Download"
> TE2-FE: Added new rules to hyperlink & renamed export to download

- app/components/navbar/nav.js
- app/components/texteditor/Texteditor.css
- public/index.css
- Edited dark mode button's color
- Deleted unused code
> T2-FE: Edited dark mode button & deleted unused code

- app/components/about/about.js
- app/components/texteditor/texteditor.js
- app/utils/auto-save.js
- public/index.css
- Updated the "About us" statement to be more up to date and added our Github link for users to contact us
- Commented out the inline styling so H1, H2, and p tags will now all be on their own separate lines.
> T2-FE: Edited About us statement & deleted inline styles

- app/components/texteditor/Texteditor.css
- app/components/texteditor/toolbar.js
This adds a drawer for the URL button.
> Editor style

- app/components/import/Dropzone.css
- app/components/texteditor/texteditor.js
- app/components/texteditor/toolbar.js
- app/utils/clearDoc.js
- app/utils/keyboard-rules.js
- Delete button with confirmation alert for clearing all contents within the document
- If the run button is deleted via backspace the associated code block is also deleted with it.
> Additional feat

- app/components/texteditor/toolbar.js
- app/utils/clearDoc.js
- User is prompted with a pop up when trying to delete a document
> T2-FE: Delete button gives pop up instead of alert

- app/components/navbar/nav.js
- User will be alerted that there is nothing to download if the text editor is empty
> T2-FE: User cannot download if text editor is empty
